# Generated by Django 5.0.4 on 2024-04-18 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created_at',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 4, 18, 7, 10, 44, 601347)),
        ),
    ]
