# Generated by Django 5.0.4 on 2024-04-18 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todolist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 18, 8, 45, 40, 649202)),
        ),
    ]
