# Generated by Django 5.0.4 on 2024-04-18 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_todolist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 4, 18)),
        ),
    ]
